"""
Constant values.
"""

# Network types
SIAMESE_BINARY = 0
SIAMESE_CONTRASTIVE = 1
SIAMESE_NTXENT = 2
SIAMESE_TRIPLET = 3
OHNM_TRIPLET = 4

# Datasets
FISH = 0
OMNIGLOT = 1

# Dataset flavours
FISH_HEAD = 0
FISH_WHOLE = 1
FISH_HEAD_LEFT = 2
FISH_HEAD_RIGHT = 3
FISH_MERGED_PAIR_LEFT = 4
FISH_MERGED_PAIR_RIGHT = 5
FISH_BINARY = 6
FISH_MERGED = 7
FISH_MERGED_LEFT = 8
FISH_MERGED_RIGHT = 9
FISH_HEAD_PAIR_LEFT = 10
FISH_HEAD_PAIR_RIGHT = 11